image: ubuntu:18.04

before_script:
  - apt-get update && apt-get -y install build-essential cmake

stages:
  - build
  - test
  - package

build:
  stage: build
  artifacts:
    untracked: true
  script:
    - mkdir build && cd build && cmake .. && make


test:
  stage: test
  dependencies:
    - build
  script:
    - cd build && yes|./EpollPlus_test

package:
  stage: package
  dependencies:
    - test
  script:
    - cd build && make package
  artifacts:
    paths:
      - "build/*.deb"
      - "build/*.rpm"
      - "build/*.xz"